// <autogenerated>
// WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
// DDS version: 3.16
// ACE version: 6.5.14
// Running on input file: IDL\TestMessage.idl
// </autogenerated>

using System;
using System.Linq;
using System.Security;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using OpenDDSharp;
using OpenDDSharp.DDS;

namespace HelloWorld
{
    #region Message Definitions
    public class Message
    {
        #region Constants
        internal const string API_DLL = "TestMessageWrapper";
        #endregion

        #region Fields
        string _Content;
        #endregion

        #region Properties
        public string Content
        {
            get { return _Content; }
            set { _Content = value; }
        }
        #endregion 

        #region Constructors
        public Message()
        {
            _Content = string.Empty;
        }
        #endregion

        #region Methods
        internal MessageWrapper ToNative(List<IntPtr> toRelease)
        {
            MessageWrapper wrapper = new MessageWrapper();

            if (Content != null)
            {
                wrapper.Content = Marshal.StringToHGlobalAnsi(Content);
                toRelease.Add(wrapper.Content);
            }

            return wrapper;
        }

        internal void FromNative(MessageWrapper wrapper)
        {
            if (wrapper.Content != IntPtr.Zero)
            {
                Content= Marshal.PtrToStringAnsi(wrapper.Content);
            }
            else
            {
                Content = null;
            }
        }
        #endregion
    }

    [StructLayout(LayoutKind.Sequential)]
    internal struct MessageWrapper
    {
        public IntPtr Content;
    }

	public class MessageTypeSupport
    {
        #region Field
        private IntPtr _native;
        #endregion

        #region Constructors
        public MessageTypeSupport()
        {
            _native = MessageTypeSupportNew();
        }
        #endregion

        #region Methods
        public string GetTypeName()
        {
            return Marshal.PtrToStringAnsi(GetTypeName(_native));
        }

        public ReturnCode RegisterType(DomainParticipant dp, string typeName)
        {
            return (ReturnCode)RegisterType(_native, dp.ToNative(), typeName);
        }

        public ReturnCode UnregisterType(DomainParticipant dp, string typeName)
        {            
            return (ReturnCode)UnregisterType(_native, dp.ToNative(), typeName);
        }
        #endregion

        #region PInvoke
        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageTypeSupport_new", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr MessageTypeSupportNew();

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageTypeSupport_GetTypeName", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Auto, BestFitMapping = false, ThrowOnUnmappableChar = true)]
        private static extern IntPtr GetTypeName(IntPtr native);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageTypeSupport_RegisterType", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true)]
        private static extern int RegisterType(IntPtr native, IntPtr dp, string typeName);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageTypeSupport_UnregisterType", CallingConvention = CallingConvention.Cdecl, CharSet = CharSet.Ansi, BestFitMapping = false, ThrowOnUnmappableChar = true)]
        private static extern int UnregisterType(IntPtr native, IntPtr dp, string typeName);
        #endregion
    }

    public class MessageDataWriter : DataWriter
    {
        #region Fields
        private readonly IntPtr _native;
        #endregion

        #region Constructors
        public MessageDataWriter(DataWriter dw) : base(dw.ToNative())
        {
			IntPtr ptr = base.ToNative();
            _native = Narrow(ptr);
        }
        #endregion

        #region Methods
        public InstanceHandle RegisterInstance(Message instance)
        {
            InstanceHandle ret = InstanceHandle.HandleNil;

            List<IntPtr> toRelease = new List<IntPtr>();
            MessageWrapper wrapper = instance.ToNative(toRelease);
            ret = RegisterInstance(_native, wrapper);

            return ret;
        }

        public InstanceHandle RegisterInstance(Message instance, Timestamp timestamp)
        {
            InstanceHandle ret = InstanceHandle.HandleNil;

            List<IntPtr> toRelease = new List<IntPtr>();
            MessageWrapper wrapper = instance.ToNative(toRelease);
            ret = RegisterInstanceTimestamp(_native, wrapper, timestamp);

            return ret;
        }

        public ReturnCode UnregisterInstance(Message data)
        {
            List<IntPtr> toRelease = new List<IntPtr>();
            HelloWorld.MessageWrapper native = data.ToNative(toRelease);

            InstanceHandle handle = LookupInstance(data);
            if (handle == InstanceHandle.HandleNil) 
            {
                return ReturnCode.PreconditionNotMet;
            }

	        return (ReturnCode)UnregisterInstance(_native, native, handle);
        }

		public ReturnCode UnregisterInstance(Message data, InstanceHandle handle)
        {
            List<IntPtr> toRelease = new List<IntPtr>();
            HelloWorld.MessageWrapper native = data.ToNative(toRelease);

            return (ReturnCode)UnregisterInstance(_native, native, handle);
        }

        public ReturnCode UnregisterInstance(Message data, InstanceHandle handle, Timestamp timestamp)
        {
            List<IntPtr> toRelease = new List<IntPtr>();
            HelloWorld.MessageWrapper native = data.ToNative(toRelease);

            return (ReturnCode)UnregisterInstanceTimestamp(_native, native, handle, timestamp);
        }

        public ReturnCode Write(Message data)
        {
            return Write(data, InstanceHandle.HandleNil);
        }

        public ReturnCode Write(Message data, InstanceHandle handle)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            List<IntPtr> toRelease = new List<IntPtr>();

            MessageWrapper wrapper = data.ToNative(toRelease);
            ret = (ReturnCode)Write(_native, wrapper, handle);

            // Always free the unmanaged memory.
            foreach (IntPtr ptr in toRelease)
            {
                Marshal.FreeHGlobal(ptr);
            }

            return ret;
        }

        public ReturnCode Write(Message data, InstanceHandle handle, Timestamp timestamp)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            List<IntPtr> toRelease = new List<IntPtr>();

            MessageWrapper wrapper = data.ToNative(toRelease);
            ret = (ReturnCode)WriteWithTimestamp(_native, wrapper, handle, timestamp);

            // Always free the unmanaged memory.
            foreach(IntPtr ptr in toRelease)
            {
                Marshal.FreeHGlobal(ptr);
            }

            return ret;
        }

        public ReturnCode Dispose(Message data)
        {
            return Dispose(data, InstanceHandle.HandleNil);
        }

		public ReturnCode Dispose(Message data, InstanceHandle handle)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            List<IntPtr> toRelease = new List<IntPtr>();

            ret = (ReturnCode)Dispose(_native, data.ToNative(toRelease), handle);

            // Always free the unmanaged memory.
            foreach (IntPtr ptr in toRelease)
            {
                Marshal.FreeHGlobal(ptr);
            }

            return ret;
        }

        public ReturnCode Dispose(Message data, InstanceHandle handle, Timestamp timestamp)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            List<IntPtr> toRelease = new List<IntPtr>();

            ret = (ReturnCode)DisposeTimestamp(_native, data.ToNative(toRelease), handle, timestamp);

            // Always free the unmanaged memory.
            foreach(IntPtr ptr in toRelease)
            {
                Marshal.FreeHGlobal(ptr);
            }

            return ret;
        }

        public ReturnCode GetKeyValue(Message data, InstanceHandle handle)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            MessageWrapper aux = new MessageWrapper();

            ret = (ReturnCode)GetKeyValue(_native, ref aux, handle);

            if (ret == ReturnCode.Ok)
            {
                data.FromNative(aux);
            }

            return ret;
        }

        public InstanceHandle LookupInstance(Message instance)
        {
            InstanceHandle ret = InstanceHandle.HandleNil;
            List<IntPtr> toRelease = new List<IntPtr>();

            ret = LookupInstance(_native, instance.ToNative(toRelease));

            // Always free the unmanaged memory.
            foreach (IntPtr ptr in toRelease)
            {
                Marshal.FreeHGlobal(ptr);
            }

            return ret;
        }
        #endregion

        #region PInvoke
        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_Narrow", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr Narrow(IntPtr dw);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_Write", CallingConvention = CallingConvention.Cdecl)]
        private static extern int Write(IntPtr dw, [MarshalAs(UnmanagedType.Struct), In] MessageWrapper data, int handle);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_WriteWithTimestamp", CallingConvention = CallingConvention.Cdecl)]
        private static extern int WriteWithTimestamp(IntPtr dw, [MarshalAs(UnmanagedType.Struct), In] MessageWrapper data, int handle, [MarshalAs(UnmanagedType.Struct), In] Timestamp timestamp);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_RegisterInstance", CallingConvention = CallingConvention.Cdecl)]
        private static extern int RegisterInstance(IntPtr dw, MessageWrapper instance);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_RegisterInstanceTimestamp", CallingConvention = CallingConvention.Cdecl)]
        private static extern int RegisterInstanceTimestamp(IntPtr dw, MessageWrapper instance, [MarshalAs(UnmanagedType.Struct), In] Timestamp timestamp);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_UnregisterInstance", CallingConvention = CallingConvention.Cdecl)]
        private static extern int UnregisterInstance(IntPtr dw, MessageWrapper instance, int handle);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_UnregisterInstanceTimestamp", CallingConvention = CallingConvention.Cdecl)]
        private static extern int UnregisterInstanceTimestamp(IntPtr dw, MessageWrapper instance, int handle, [MarshalAs(UnmanagedType.Struct), In] Timestamp timestamp);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_LookupInstance", CallingConvention = CallingConvention.Cdecl)]
        private static extern int LookupInstance(IntPtr dw, MessageWrapper instance);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_Dispose", CallingConvention = CallingConvention.Cdecl)]
        private static extern int Dispose(IntPtr dw, [MarshalAs(UnmanagedType.Struct), In] MessageWrapper data, int handle);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_DisposeTimestamp", CallingConvention = CallingConvention.Cdecl)]
        private static extern int DisposeTimestamp(IntPtr dw, [MarshalAs(UnmanagedType.Struct), In] MessageWrapper data, int handle, [MarshalAs(UnmanagedType.Struct), In] Timestamp timestamp);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataWriter_GetKeyValue", CallingConvention = CallingConvention.Cdecl)]
        private static extern int GetKeyValue(IntPtr dw, [MarshalAs(UnmanagedType.Struct), In, Out] ref MessageWrapper data, int handle);
        #endregion
    }

    public class MessageDataReader : DataReader
    {
        #region Fields
        private readonly IntPtr _native;
        #endregion

        #region Constructors
        public MessageDataReader(DataReader dr) : base(dr.ToNative())
        {
			IntPtr ptr = base.ToNative();
            _native = Narrow(ptr);
        }
        #endregion

        #region Methods
        public ReturnCode Read(List<Message> receivedData, List<SampleInfo> receivedInfo)
        {
            return Read(receivedData, receivedInfo, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

        public ReturnCode Read(List<Message> receivedData, List<SampleInfo> receivedInfo, int maxSamples)
        {
            return Read(receivedData, receivedInfo, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

        public ReturnCode Read(List<Message> receivedData, List<SampleInfo> receivedInfo, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)ReadWithCondition(_native, ref rd, ref ri, maxSamples, condition.ToNative());
            
            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode Read(List<Message> receivedData, List<SampleInfo> receivedInfo, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)Read(_native, ref rd, ref ri, maxSamples, sampleStates, viewStates, instanceStates);            

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode Take(List<Message> receivedData, List<SampleInfo> receivedInfo)
        {
            return Take(receivedData, receivedInfo, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

        public ReturnCode Take(List<Message> receivedData, List<SampleInfo> receivedInfo, int maxSamples)
        {
            return Take(receivedData, receivedInfo, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

        public ReturnCode Take(List<Message> receivedData, List<SampleInfo> receivedInfo, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)TakeWithCondition(_native, ref rd, ref ri, maxSamples, condition.ToNative());            

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode Take(List<Message> receivedData, List<SampleInfo> receivedInfo, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)Take(_native, ref rd, ref ri, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode ReadInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle)
        {
            return ReadInstance(receivedData, receivedInfo, handle, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode ReadInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples)
        {
            return ReadInstance(receivedData, receivedInfo, handle, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode ReadInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)ReadInstanceWithCondition(_native, ref rd, ref ri, (int)handle, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode ReadInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)ReadInstance(_native, ref rd, ref ri, handle, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode TakeInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle)
        {
            return TakeInstance(receivedData, receivedInfo, handle, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode TakeInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples)
        {
            return TakeInstance(receivedData, receivedInfo, handle, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode TakeInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)TakeInstanceWithCondition(_native, ref rd, ref ri, (int)handle, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode TakeInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle handle, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)TakeInstance(_native, ref rd, ref ri, handle, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode ReadNextInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle)
        {
            return ReadNextInstance(receivedData, receivedInfo, previousHandle, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode ReadNextInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples)
        {
            return ReadNextInstance(receivedData, receivedInfo, previousHandle, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode ReadNextInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)ReadNextInstanceWithCondition(_native, ref rd, ref ri, previousHandle, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode ReadNextInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)ReadNextInstance(_native, ref rd, ref ri, previousHandle, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode TakeNextInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle)
        {
            return TakeNextInstance(receivedData, receivedInfo, previousHandle, ResourceLimitsQosPolicy.LengthUnlimited, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode TakeNextInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples)
        {
            return TakeNextInstance(receivedData, receivedInfo, previousHandle, maxSamples, SampleStateMask.AnySampleState, ViewStateMask.AnyViewState, InstanceStateMask.AnyInstanceState);
        }

		public ReturnCode TakeNextInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples, ReadCondition condition)
        {
            if (condition == null)
            {
                return ReturnCode.BadParameter;
            }

            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)TakeNextInstanceWithCondition(_native, ref rd, ref ri, previousHandle, maxSamples, condition.ToNative());

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode TakeNextInstance(List<Message> receivedData, List<SampleInfo> receivedInfo, InstanceHandle previousHandle, int maxSamples, SampleStateMask sampleStates, ViewStateMask viewStates, InstanceStateMask instanceStates)
        {
            if (receivedData == null || receivedInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            receivedData.Clear();
            receivedInfo.Clear();

            IntPtr rd = IntPtr.Zero;
            IntPtr ri = IntPtr.Zero;

            ReturnCode ret = ReturnCode.Error;
            ret = (ReturnCode)TakeNextInstance(_native, ref rd, ref ri, previousHandle, maxSamples, sampleStates, viewStates, instanceStates);

            if (ret == ReturnCode.Ok && !rd.Equals(IntPtr.Zero) && !ri.Equals(IntPtr.Zero))
            {
                IList<MessageWrapper> data = new List<MessageWrapper>();
                IList<SampleInfoWrapper> info = new List<SampleInfoWrapper>();

                MarshalHelper.PtrToSequence(rd, ref data);
                MarshalHelper.PtrToSequence(ri, ref info);

                if (data != null)
                {
                    foreach (var d in data)
                    {
                        var aux = new Message();
                        aux.FromNative(d);
                        receivedData.Add(aux);
                    }
                }

                if (info != null && info.Count > 0)
                {
                    foreach (var i in info)
                    {
                        SampleInfo aux = new SampleInfo();
                        aux.FromNative(i);
                        receivedInfo.Add(aux);
                    }
                }
            }

            return ret;
        }

        public ReturnCode ReadNextSample(Message data, SampleInfo sampleInfo)
        {
            if (data == null || sampleInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            MessageWrapper wrapper = new MessageWrapper();
            SampleInfoWrapper infoWrapper = new SampleInfoWrapper();
            ret = (ReturnCode)ReadNextSample(_native, ref wrapper, ref infoWrapper);
            if (ret == ReturnCode.Ok)
            {
                data.FromNative(wrapper);
                sampleInfo.FromNative(infoWrapper);

                // Always free the unmanaged memory.
                // As the unmanaged memory was reserved in C++ we need a method to release it from C++.
                Release(ref wrapper);
            }

            return ret;
        }

        public ReturnCode TakeNextSample(Message data, SampleInfo sampleInfo)
        {
            if (data == null || sampleInfo == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            MessageWrapper wrapper = new MessageWrapper();
            SampleInfoWrapper infoWrapper = new SampleInfoWrapper();
            ret = (ReturnCode)TakeNextSample(_native, ref wrapper, ref infoWrapper);
            if (ret == ReturnCode.Ok)
            {
                data.FromNative(wrapper);
                sampleInfo.FromNative(infoWrapper);

                // Always free the unmanaged memory.
                // As the unmanaged memory was reserved in C++ we need a method to release it from C++.
                Release(ref wrapper);
            }

            return ret;
        }

        public ReturnCode GetKeyValue(Message data, InstanceHandle handle)
        {
            if (data == null)
            {
                return ReturnCode.BadParameter;
            }

            ReturnCode ret = ReturnCode.Error;
            MessageWrapper aux = new MessageWrapper();

            ret = (ReturnCode)GetKeyValue(_native, ref aux, handle);            

            if (ret == ReturnCode.Ok)
            {
                data.FromNative(aux);
            }

            return ret;
        }

        public InstanceHandle LookupInstance(Message instance)
        {
            InstanceHandle ret = InstanceHandle.HandleNil;
            List<IntPtr> toRelease = new List<IntPtr>();

            ret = LookupInstance(_native, instance.ToNative(toRelease));

            // Always free the unmanaged memory.
            foreach (IntPtr ptr in toRelease)
            {
                Marshal.FreeHGlobal(ptr);
            }

            return ret;
        }
        #endregion

        #region PInvoke
        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageWrapper_release", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr Release([MarshalAs(UnmanagedType.Struct), In, Out] ref MessageWrapper data);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_Narrow", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr Narrow(IntPtr dr);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_Read", CallingConvention = CallingConvention.Cdecl)]
        private static extern int Read(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_ReadWithCondition", CallingConvention = CallingConvention.Cdecl)]
        private static extern int ReadWithCondition(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_Take", CallingConvention = CallingConvention.Cdecl)]
        private static extern int Take(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_TakeWithCondition", CallingConvention = CallingConvention.Cdecl)]
        private static extern int TakeWithCondition(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_ReadInstance", CallingConvention = CallingConvention.Cdecl)]
        private static extern int ReadInstance(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_ReadInstanceWithCondition", CallingConvention = CallingConvention.Cdecl)]
        private static extern int ReadInstanceWithCondition(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_TakeInstance", CallingConvention = CallingConvention.Cdecl)]
        private static extern int TakeInstance(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_TakeInstanceWithCondition", CallingConvention = CallingConvention.Cdecl)]
        private static extern int TakeInstanceWithCondition(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_ReadNextInstance", CallingConvention = CallingConvention.Cdecl)]
        private static extern int ReadNextInstance(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_ReadNextInstanceWithCondition", CallingConvention = CallingConvention.Cdecl)]
        private static extern int ReadNextInstanceWithCondition(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_TakeNextInstance", CallingConvention = CallingConvention.Cdecl)]
        private static extern int TakeNextInstance(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int handle, int maxSamples, uint sampleStates, uint viewStates, uint instanceStates);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_TakeNextInstanceWithCondition", CallingConvention = CallingConvention.Cdecl)]
        private static extern int TakeNextInstanceWithCondition(IntPtr dr, ref IntPtr receivedData, ref IntPtr receivedInfo, int handle, int maxSamples, IntPtr condition);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_ReadNextSample", CallingConvention = CallingConvention.Cdecl)]
        private static extern int ReadNextSample(IntPtr dr, [MarshalAs(UnmanagedType.Struct), In, Out] ref MessageWrapper data, [In, Out] ref SampleInfoWrapper sampleInfo);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_TakeNextSample", CallingConvention = CallingConvention.Cdecl)]
        private static extern int TakeNextSample(IntPtr dr, [MarshalAs(UnmanagedType.Struct), In, Out] ref MessageWrapper data, [In, Out] ref SampleInfoWrapper sampleInfo);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_LookupInstance", CallingConvention = CallingConvention.Cdecl)]
        private static extern int LookupInstance(IntPtr dr, MessageWrapper instance);

        [SuppressUnmanagedCodeSecurity]
        [DllImport(Message.API_DLL, EntryPoint = "HelloWorld_MessageDataReader_GetKeyValue", CallingConvention = CallingConvention.Cdecl)]
        private static extern int GetKeyValue(IntPtr dr, [MarshalAs(UnmanagedType.Struct), In, Out] ref MessageWrapper data, int handle);
        #endregion
    }
    #endregion

}
